version: '3.8'

services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: paintings_db
    ports:
      - "5432:5432"  # Exposes PostgreSQL locally
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "8080:8080"   # HTTP port for local testing
      - "8443:8443"   # HTTPS port for local testing
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/paintings_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      PORT: 8080  # Sets the default port for local environment
    depends_on:
      - db
    restart: unless-stopped

volumes:
  db_data:
