

services:
  postgres_container:
    image: postgres:14
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./paintings.csv:/docker-entrypoint-initdb.d/paintings.csv
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U my_user -d my_database"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-docker:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_container:5432/my_database
      SPRING_DATASOURCE_USERNAME: my_user
      SPRING_DATASOURCE_PASSWORD: my_password
      PORT: 8443
    ports:
      - "8443:8443"
    depends_on:
      postgres_container:
        condition: service_healthy
